server:
  port: 8085

eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8081/eureka/

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MolyXl/config.git
          searchPaths: cloud/helloworldConfig
  application:
    name: eureka-config